### Mathemetical Operations


In [2]:
import numpy as np 

arr1 = np.array([[30,40],[20,10]])
arr2 = np.array([[30,20],[20,20]])
print(arr1+arr2)
print(np.add(arr1,arr2))

[[60 60]
 [40 30]]
[[60 60]
 [40 30]]


In [3]:
import numpy as np 

arr1 = np.array([[30,40],[20,10]])
arr2 = np.array([[30,20],[20,20]])
print(arr1-arr2)
print(np.subtract(arr1,arr2))

[[  0  20]
 [  0 -10]]
[[  0  20]
 [  0 -10]]


In [4]:
import numpy as np 

arr1 = np.array([[30,40],[20,10]])
arr2 = np.array([[30,20],[20,20]])
print(arr1*arr2)
print(np.multiply(arr1,arr2))

[[900 800]
 [400 200]]
[[900 800]
 [400 200]]


In [5]:
import numpy as np 

arr1 = np.array([[30,40],[20,10]])
arr2 = np.array([[30,20],[20,20]])
print(arr1/arr2)
print(np.divide(arr1,arr2))

[[1.  2. ]
 [1.  0.5]]
[[1.  2. ]
 [1.  0.5]]


In [6]:
arr1 = np.array([3,4,2,1])
arr2 = np.array([2])
print(np.power(arr1,arr2))

[ 9 16  4  1]


In [9]:
arr1 = np.array([9,16, 4, 1])
print(np.sqrt(arr1))

[3. 4. 2. 1.]
