### Adding and Removing

In [5]:
import numpy as np 

a = np.array([[20,40],[50,80]])
print(np.append(a,[90,100]))

[ 20  40  50  80  90 100]


In [10]:
print(np.insert(a,1,[50], axis=1)) # array, index, value

[[20 50 40]
 [50 50 80]]


In [17]:
print(a)
print()
print(np.delete(a,1, axis=1))

[[20 40]
 [50 80]]

[[20]
 [50]]
