In [3]:
import numpy as np 

a = np.array([20, 30, 40])
b = np.array([60, 70, 80])

print(a)
print(b)
print(a + b)

[20 30 40]
[60 70 80]
[ 80 100 120]


In [5]:
a = np.array([20, 30, 80.0])
print(a)

[20. 30. 80.]


In [6]:
l1 = [[20, 30], [20, 30, 40]]
print(l1)

[[20, 30], [20, 30, 40]]


In [7]:
l2 = np.array([[20,30], [20, 40, 50]])
print(l2)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

### Numpy - Creating Arrays, Slicing, and Attributes 